/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#735c00",
        "on-tertiary-fixed-variant": "#574500",
        "primary-fixed-dim": "#9fcee0",
        primary: "#003643",
        outline: "#71787c",
        "on-background": "#1a1c1b",
        "secondary-fixed": "#cee9da",
        "inverse-on-surface": "#f1f1ef",
        "surface-container-low": "#f4f3f1",
        background: "#faf9f7",
        "on-error": "#ffffff",
        "on-secondary-container": "#52695e",
        "surface-container-high": "#e9e8e6",
        "surface-container": "#efeeec",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001f28",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#354c41",
        "error-container": "#ffdad6",
        "primary-fixed": "#baeafc",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary": "#ffffff",
        "on-surface": "#1a1c1b",
        "inverse-surface": "#2f3130",
        "on-tertiary-container": "#4f3d00",
        "on-error-container": "#93000a",
        "surface-dim": "#dadad8",
        "tertiary-container": "#cca730",
        "secondary-container": "#cee9da",
        "surface-tint": "#366574",
        "on-surface-variant": "#41484b",
        "on-primary-container": "#8ebdce",
        "surface-variant": "#e3e2e0",
        surface: "#faf9f7",
        "on-secondary": "#ffffff",
        secondary: "#4c6358",
        "surface-bright": "#faf9f7",
        "on-primary-fixed-variant": "#1a4d5c",
        "tertiary-fixed": "#ffe088",
        "inverse-primary": "#9fcee0",
        "secondary-fixed-dim": "#b3ccbf",
        "primary-container": "#1b4d5c",
        "surface-container-highest": "#e3e2e0",
        "on-tertiary-fixed": "#241a00",
        "on-secondary-fixed": "#092017",
        "outline-variant": "#c0c8cb",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "margin-mobile": "20px",
        "section-padding": "80px",
        base: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "display-lg": ["Manrope"],
        "title-md": ["Manrope"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-sm": ["13px", { lineHeight: "16px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      padding: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
    },
  },
  plugins: [],
}
