const PDFDocument = require('pdfkit');
const ChatbotSummary = require('../models/ChatbotSummary');
const Session = require('../models/Session');
const User = require('../models/User');

// @GET /api/sessions/:id/report/pdf
exports.generatePDF = async (req, res) => {
  try {
    const sessionId = req.params.id;

    const summary = await ChatbotSummary.findOne({ sessionId });
    if (!summary) return res.status(404).json({ message: 'Summary not found' });

    const session = await Session.findById(sessionId);
    const patient = await User.findById(session.patientId).select('email');

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=report-' + sessionId + '.pdf');

    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('Psychological Pre-Interview Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).font('Helvetica').fillColor('#666666').text('Generated by Psych Platform — AI Assisted', { align: 'center' });
    doc.moveDown();

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown();

    // Patient Info
    doc.fontSize(13).font('Helvetica-Bold').fillColor('#000000').text('Patient Information');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica').text('Email: ' + patient.email);
    doc.text('Session ID: ' + sessionId);
    doc.text('Session Type: ' + session.sessionType);
    doc.text('Date: ' + new Date(summary.createdAt).toLocaleDateString());
    doc.moveDown();

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown();

    // Emotional Indicators
    doc.fontSize(13).font('Helvetica-Bold').text('Emotional Indicators');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text('Dominant Emotion: ' + summary.emotionalIndicators.dominantEmotion);
    doc.text('Urgency Score: ' + summary.emotionalIndicators.urgencyScore + ' / 5');
    doc.text('Sentiment Trend: ' + summary.emotionalIndicators.sentimentTrend);
    doc.moveDown();

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown();

    // Key Themes
    doc.fontSize(13).font('Helvetica-Bold').text('Key Themes');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    summary.keyThemes.forEach(theme => {
      doc.text('• ' + theme);
    });
    doc.moveDown();

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown();

    // Clinical Summary
    doc.fontSize(13).font('Helvetica-Bold').text('Clinical Summary');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica').text(summary.rawSummary, { lineGap: 4 });
    doc.moveDown();

    // Footer
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown();
    doc.fontSize(9).fillColor('#999999').text('This report was generated automatically by an AI assistant. It is intended to assist the psychologist and does not constitute a medical diagnosis.', { align: 'center', lineGap: 3 });

    doc.end();

  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
};