const mongoose = require('mongoose');

/**
 * Model: IntakeSession
 * Tracks the state of a patient's psychological intake session with the chatbot.
 * One active IntakeSession per patient at a time — resets when definitively ended.
 */
const intakeSessionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },
    currentStage: {
      type: Number,
      default: 1,
      min: 1,
      max: 5
    },
    stageTurnCounts: {
      type: Map,
      of: Number,
      default: () => new Map([['1', 0], ['2', 0], ['3', 0], ['4', 0], ['5', 0]])
    },
    isComplete: {
      type: Boolean,
      default: false
    },

    // ── Crisis hold ──────────────────────────────────────────────────────
    // Set to true when consecutiveRiskCount reaches CRISIS_HOLD_THRESHOLD
    // (currently 2) in chatRoute.js. When true:
    //   - Every subsequent message gets the escalation response
    //   - The normal RAG pipeline does not run
    //   - Chatbot.jsx shows the holding screen instead of the input footer
    //   - /api/chat/init returns crisisHold: true so page reloads respect it
    // Cleared only by an explicit reset (dev/testing) or psychologist clearance.
    crisisHold: {
      type: Boolean,
      default: false
    },

    // ── Risk tracking ────────────────────────────────────────────────────
    // consecutiveRiskCount: incremented each HIGH risk turn, reset to 0
    // on any non-HIGH turn. Triggers crisisHold when it hits the threshold.
    consecutiveRiskCount: {
      type: Number,
      default: 0
    },
    lastRiskCategory: {
      type: String,
      default: null
    },
    lastRiskAt: {
      type: Date,
      default: null
    },

    // ── Rolling context window ───────────────────────────────────────────
    // contextSummary: LLM-compressed clinical summary of turns older than
    // the recent RECENT_TURN_LIMIT window. Generated by compressEarlyContext()
    // in chatRoute.js after each turn (non-blocking). Injected into the LLM
    // prompt by GenerateEmpatheticResponse.js so early disclosures (trauma,
    // suicidal ideation from stage 1) are never silently dropped.
    contextSummary: {
      type: String,
      default: null
    },
    contextSummaryUpdatedAt: {
      type: Date,
      default: null
    },
    usedExampleIds: {
      type: [String],
      default: []
    },

    // ── Session lifecycle ────────────────────────────────────────────────
    startedAt: {
      type: Date,
      default: Date.now
    },
    completedAt: {
      type: Date,
      default: null
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model('IntakeSession', intakeSessionSchema);